### ISSUE TITLE
Error: Cannot find module 'vsts-task-lib'

### ISSUE THREAD

**Issue by zulalay** [Microsoft/vsts-task-lib#64]
Hey guys.
Everything worked fine untill today. And now when i add Cordova Command to my build steps i get
Set workingFolder to default: D:\agent\tasks\CordovaCommand\1.2.0
 
module.js:338
throw err;
Error: Cannot find module 'vsts-task-lib'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
 
at Object.<anonymous> (D:\agent\tasks\CordovaCommand\1.2.0\lib\vsts-task-lib-proxy.js:35:7)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)

any ideas or hint where should i look at?

**Comment by Jonlondon** [comment]
Hi, I got the same issue.

**Comment by chrisrpatterson** [comment]
Where did the CordovaCommand task come from?  They should be including that module in their package.

**Comment by bryanmacfarlane** [comment]
This is an issue in the cordova task.  It's the one that can't find the task lib via it's proxy. It's not an issue with the lib that the consumer can't find it.
